# DEV, PROD value on AWS
server:
  port: 8090
custom:
  secret: ${SECRET}
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /api-docs
spring:
  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: Asia/Seoul
      connection:
        characterEncoding: UTF8
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true