# DEV, PROD value on AWS
server:
  port: 8090
custom:
  secret: ${CUSTOM_SECRET}
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /api-docs
spring:
  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: Asia/Seoul
      connection:
        characterEncoding: UTF8
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  level:
    root: error

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  push:
    region: ${AWS_PUSH_REGION}
  sms:
    region: ${AWS_SMS_REGION}

slack:
  channelId: ${SLACK_MESSAGE_CHANNEL}
  token: ${SLACK_TOKEN}